[versions]
kotlin = "1.9.10"
androidGradlePlugin = "8.2.0"
tflite = "2.12.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.10.1"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
androidx-material3 = "com.google.android.material:material:1.9.0"
tflite = "org.tensorflow:tensorflow-lite:2.12.0"

# Testing Libraries
junit = "junit:junit:4.13.2"
androidx-junit = "androidx.test.ext:junit:1.1.5"
androidx-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
